### ISSUE TITLE
CUPS printing is broken

### ISSUE THREAD

**Issue by davygravy** [Entware/Entware#270]
First, thank you AR, Zyxmon and others for continuing to do this work.  It is appreciated.

It appears that CUPS printing functionality is broken in the current 2.2.10-1 release.   This "issue" may have many components, but I felt this was a good place to start.

After installing CUPS, modifying its config file (cupds.conf and cups-files.conf), setting up proper users (nobody), etc.,  attaching a printer and working for over 1 week now trying to troubleshoot it, I've been unable to get anything to print via CUPS.

Known working:
-  HP USB printer tested, works via p910nd, so it is known as functional
-  installing CUPS:  Install goes fine, along with the dependent packages.
-  CUPS server runs, log level is set to debug, webinterface (:631) functions partly

Know not functional/problems/missing:
-  all basic lpr printing from the command line : literally nothing prints [ error : lp: Unsupported format 'text/plain' ]
-  missing components (printer test page, for example, and many other items) missing from proper
-  libcupsppdc.so.* ,  libcupsmime.so.* ,  libcupscgi.so.*  [I read your changelog and see that these were intended to merge with libcups.   libcupsimage.so.*  **IS** present, but not the three listed above]
-  it appears to me that a large portion of cups-filters is missing : the older packages that I have seem to be much larger
-   error log full of "Filter failed" messages

Unknown: 
- were there some missed dependencies?
- is Ghostscript fully functional?

Best Guess of Problem Origin:
-  missing CUPS components (known to be true)
-  missing or broken cups-filters 

Alexander, please let me know how I can help.

Dave

**Comment by davygravy** [comment]
From CUPS error_log:

"Unable to execute ippfind utility: No such file or directory"
- driverless printing is pretty much broken/useless without the ippfind utility, so this binary ippfind is pretty essential

**Comment by davygravy** [comment]
In cups-filters, reinstating:

~~`PKG_BUILD_DEPENDS:=libijs`~~
	$(INSTALL_DIR) $(1)/opt/share
	$(CP) $(PKG_INSTALL_DIR)/opt/share/* $(1)/opt/share 


after line 77 and rebuilding the package seems to fix  **fixes the "Filter failed" error** 
```
echo hello | lp
request id is HPC4480-3 (0 file(s))
```
Doesn't throw an error now... but CUPS says it has no viable font:

Next error is:
```
D [15/Apr/2019:14:51:25 +0000] [Job 3] No viable font found
W [15/Apr/2019:14:51:25 +0000] [Job 3] Ignored bad font \"monospace\"
D [15/Apr/2019:14:51:25 +0000] cupsdMarkDirty(---J-)
D [15/Apr/2019:14:51:25 +0000] cupsdSetBusyState: newbusy="Printing jobs and dirty files", busy="Printing jobs and dirty files"
D [15/Apr/2019:14:51:25 +0000] [Job 3] Set job-printer-state-message to "Ignored bad font \"monospace\"", current level=WARN
D [15/Apr/2019:14:51:25 +0000] Discarding unused job-progress event...
D [15/Apr/2019:14:51:25 +0000] Discarding unused printer-state-changed event...
D [15/Apr/2019:14:51:25 +0000] [Job 3] No viable font found
W [15/Apr/2019:14:51:25 +0000] [Job 3] Ignored bad font \"monospace\"
E [15/Apr/2019:14:51:25 +0000] [Job 3] No usable font available
D [15/Apr/2019:14:51:25 +0000] cupsdMarkDirty(---J-)
D [15/Apr/2019:14:51:25 +0000] cupsdSetBusyState: newbusy="Printing jobs and dirty files", busy="Printing jobs and dirty files"
D [15/Apr/2019:14:51:25 +0000] [Job 3] Set job-printer-state-message to "No usable font available", current level=ERROR
```

```
D [15/Apr/2019:14:51:34 +0000] [CGI] envp[2] = "CUPS_DOCROOT=/opt/share/doc/cups"
D [15/Apr/2019:14:51:34 +0000] [CGI] envp[3] = "CUPS_FONTPATH=/opt/share/cups/fonts"
D [15/Apr/2019:14:51:34 +0000] [CGI] envp[4] = "CUPS_REQUESTROOT=/opt/var/spool/cups"
```
/opt/share/cups/fonts  doesn't exist.

**This was a red herring...  the real problem is that there was no font installed.**

**Comment by ryzhovau** [comment]
Thanks for feedback! I'll keep this issue open, as the only one witch printing related problems.

PDF and/or printing packages was heavily [reworked](https://t.me/Entware/3474) recently. Our CUPS was [replaced](https://github.com/Entware/entware-oldpackages-ports/commit/8e2e3afc28b1efb43aba98c79d97c68b5eeca6b9#diff-f39c3734919a8bd6e8214ba36422eb41) by [CUPS from upstream](https://github.com/openwrt/packages/tree/master/libs/libcups), but my answers below is about both new and old variants. In most cases, it was balance between monstrous dependencies and user comfort. Please, don't expect the same environment as in full-blown linux desktop, still, I'll be glad to find out how to improve printing packages without being overbloated.

* web interface was never fully functional on embedded devices, neither now, nor before. It uses some system utilities and perl/pyhon scripts which is often absent on NAS/routers.
* ippfind utility was never present on OpenWrt/Entware to avoid Avahi dependency. So, driver presumed to be configured manually.
* dejavu-fonts-ttf was never present in Entware, should we add it? I deleted obsolete liberation and ubuntu fonts recently, you can still install it from archive. I can't provide wide range of desired fonts, so, which one should I provide as essential one?
* How `libijs` enhances `cups-filters`? Is it really necessary?
* `ghostscript` is working, at least as PDF transformation tool, I never used it as a printing tool.

The most common CUPS mistakes is related to missing `/opt/...` paths from hard-coded binary parts and configs. Please, let me know where I can fix them too. 

Thanks again, Dave.

**Comment by davygravy** [comment]
Spasibo, Alexander:

- the webif is pretty good as is... good enough.  The only thing that was missing for user-experience (in my humble opinion) was the test-print page - it seems useful that an end user can test the function via webif.  The patch below  puts that in without costing very much space/complexity at all.
- I was mistaken about ippfind utility being necessary.  As long as the user knows some basics (and doesn't need AirPrint for instance), then it is fine without it.
- The "liberation font" in archives will be fine.
- libijs is not needed, as I now understand.  It was used with foomatic, which I don't think is supported/used much now.   The problem with cups-filters was elsewhere... missing components in /opt/share... most of the missing components allow it to interact with Ghostscript and CUPS.
- Ghostscript is fixed now, with the change you made to detect CUPS so that the cups device is built-in.

Privyet,
Dave

**Comment by davygravy** [comment]
Comparing what worked as expected (perfectly in fact) in CUPS 2.1.4:
```
D [11/Mar/2019:16:51:38 +0000] [Job 62] envp[22]=\"CONTENT_TYPE=application/vnd.cups-pdf-banner\"
D [11/Mar/2019:16:51:38 +0000] [Job 62] envp[23]=\"DEVICE_URI=socket://127.0.0.1:9100\"
D [11/Mar/2019:16:51:38 +0000] [Job 62] envp[24]=\"PRINTER_INFO=HPC4480p910nd printer on AirDisk\"
D [11/Mar/2019:16:51:38 +0000] [Job 62] envp[25]=\"PRINTER_LOCATION=BasementOffice\"
D [11/Mar/2019:16:51:38 +0000] [Job 62] envp[26]=\"PRINTER=HPC4480@AirDisk1:9100\"
D [11/Mar/2019:16:51:38 +0000] [Job 62] envp[27]=\"PRINTER_STATE_REASONS=none\"
D [11/Mar/2019:16:51:38 +0000] [Job 62] envp[28]=\"CUPS_FILETYPE=document\"
D [11/Mar/2019:16:51:38 +0000] [Job 62] envp[29]=\"FINAL_CONTENT_TYPE=application/vnd.cups-raster\"
D [11/Mar/2019:16:51:38 +0000] [Job 62] envp[30]=\"AUTH_INFO_REQUIRED=none\"
I [11/Mar/2019:16:51:39 +0000] [Job 62] Start rendering...
D [11/Mar/2019:16:51:39 +0000] cupsdMarkDirty(---J-)
D [11/Mar/2019:16:51:39 +0000] cupsdSetBusyState: newbusy="Dirty files", busy="Dirty files"
D [11/Mar/2019:16:51:39 +0000] [Job 62] Set job-printer-state-message to "Start rendering...", current level=INFO
D [11/Mar/2019:16:51:39 +0000] Discarding unused job-progress event...
D [11/Mar/2019:16:51:39 +0000] Discarding unused printer-state-changed event...
I [11/Mar/2019:16:51:39 +0000] [Job 62] Processing page 1...
D [11/Mar/2019:16:51:39 +0000] cupsdMarkDirty(---J-)
D [11/Mar/2019:16:51:39 +0000] cupsdSetBusyState: newbusy="Dirty files", busy="Dirty files"
D [11/Mar/2019:16:51:39 +0000] [Job 62] Set job-printer-state-message to "Processing page 1...", current level=INFO
D [11/Mar/2019:16:51:39 +0000] Discarding unused job-progress event...
D [11/Mar/2019:16:51:39 +0000] Discarding unused printer-state-changed event...
D [11/Mar/2019:16:51:40 +0000] [Client 1] GET /printers/HPC4480@AirDisk1:9100 HTTP/1.1
D [11/Mar/2019:16:51:40 +0000] cupsdSetBusyState: newbusy="Active clients and dirty files", busy="Dirty files"
D [11/Mar/2019:16:51:40 +0000] [Client 1] Read: status=200
D [11/Mar/2019:16:51:40 +0000] [Client 1] No authentication data provided.
D [11/Mar/2019:16:51:40 +0000] [Client 1] Processing GET /printers/HPC4480@AirDisk1:9100
D [11/Mar/2019:16:51:40 +0000] [CGI] argv[0] = "/opt/lib/cups/cgi-bin/printers.cgi"
D [11/Mar/2019:16:51:40 +0000] [CGI] envp[0] = "CUPS_CACHEDIR=/opt/var/cache/cups"
D [11/Mar/2019:16:51:40 +0000] [CGI] envp[1] = "CUPS_DATADIR=/opt/share/cups"
D [11/Mar/2019:16:51:40 +0000] [CGI] envp[2] = "CUPS_DOCROOT=/opt/share/doc/cups"
D [11/Mar/2019:16:51:40 +0000] [CGI] envp[3] = "CUPS_FONTPATH=/opt/share/cups/fonts"
D [11/Mar/2019:16:51:40 +0000] [CGI] envp[4] = "CUPS_REQUESTROOT=/opt/var/spool/cups"
D [11/Mar/2019:16:51:40 +0000] [CGI] envp[5] = "CUPS_SERVERBIN=/opt/lib/cups"

```
to what I'm seeing in 2.2.10:
```
D [16/Apr/2019:00:19:16 +0000] [Job 22] envp[22]=\"CONTENT_TYPE=application/vnd.cups-pdf-banner\"
D [16/Apr/2019:00:19:16 +0000] [Job 22] envp[23]=\"DEVICE_URI=socket://127.0.0.1:9100\"
D [16/Apr/2019:00:19:16 +0000] [Job 22] envp[24]=\"PRINTER_INFO=HP Color Photosmart C4480 USB Printer\"
D [16/Apr/2019:00:19:16 +0000] [Job 22] envp[25]=\"PRINTER_LOCATION=Basement Office\"
D [16/Apr/2019:00:19:16 +0000] [Job 22] envp[26]=\"PRINTER=HPC4480\"
D [16/Apr/2019:00:19:16 +0000] [Job 22] envp[27]=\"PRINTER_STATE_REASONS=none\"
D [16/Apr/2019:00:19:16 +0000] [Job 22] envp[28]=\"CUPS_FILETYPE=document\"
D [16/Apr/2019:00:19:16 +0000] [Job 22] envp[29]=\"FINAL_CONTENT_TYPE=application/vnd.cups-raster\"
D [16/Apr/2019:00:19:16 +0000] [Job 22] envp[30]=\"AUTH_INFO_REQUIRED=none\"
D [16/Apr/2019:00:19:16 +0000] [Job 22] Unknown device: cups   <<<<<=========== MISSING GS DEVICE
D [16/Apr/2019:00:19:16 +0000] [Job 22] prnt/hpcups/HPCupsFilter.cpp 569: cupsRasterOpen failed, fd = 0
D [16/Apr/2019:00:19:16 +0000] [Job 22] PID 1501 (/opt/lib/cups/filter/gstoraster) stopped with status 1.
D [16/Apr/2019:00:19:16 +0000] [Job 22] PID 1502 (/opt/lib/cups/filter/hpcups) stopped with status 1.
D [16/Apr/2019:00:19:17 +0000] [Client 24] GET /printers/HPC4480 HTTP/1.1
D [16/Apr/2019:00:19:17 +0000] cupsdSetBusyState: newbusy="Active clients, printing jobs, and dirty files", busy="Printing jobs and dirty files"
D [16/Apr/2019:00:19:17 +0000] [Client 24] Read: status=200, state=3
D [16/Apr/2019:00:19:17 +0000] [Client 24] Authorized as "root" using Basic.
D [16/Apr/2019:00:19:17 +0000] [Client 24] Processing GET /printers/HPC4480
D [16/Apr/2019:00:19:17 +0000] [CGI] argv[0] = "/opt/lib/cups/cgi-bin/printers.cgi"
D [16/Apr/2019:00:19:17 +0000] [CGI] envp[0] = "CUPS_CACHEDIR=/opt/var/cache/cups"
D [16/Apr/2019:00:19:17 +0000] [CGI] envp[1] = "CUPS_DATADIR=/opt/share/cups"
D [16/Apr/2019:00:19:17 +0000] [CGI] envp[2] = "CUPS_DOCROOT=/opt/share/doc/cups"
D [16/Apr/2019:00:19:17 +0000] [CGI] envp[3] = "CUPS_FONTPATH=/opt/share/fonts"
D [16/Apr/2019:00:19:17 +0000] [CGI] envp[4] = "CUPS_REQUESTROOT=/opt/var/spool/cups"
D [16/Apr/2019:00:19:17 +0000] [CGI] envp[5] = "CUPS_SERVERBIN=/opt/lib/cups"
```

**Comment by davygravy** [comment]
I believe I've worked around all the other problems, except this one above... Ghostscript is missing its CUPS device.  In the output below, you can see that it is missing... should the last item beginning with "c", before the "d"'s start...
```
GPL Ghostscript 9.26 (2018-11-20)
Copyright (C) 2018 Artifex Software, Inc.  All rights reserved.
Usage: gs [switches] [file1.ps file2.ps ...]
Most frequently used switches: (you can use # in place of =)
 -dNOPAUSE           no pause after page   | -q       `quiet', fewer messages
 -g<width>x<height>  page size in pixels   | -r<res>  pixels/inch resolution
 -sDEVICE=<devname>  select device         | -dBATCH  exit after last file
 -sOutputFile=<file> select output file: - for stdout, |command for pipe,
                                         embed %d or %ld for page #
Input formats: PostScript PostScriptLevel1 PostScriptLevel2 PostScriptLevel3 PDF
Default output device: bbox
Available devices:
   alc1900 alc2000 alc4000 alc4100 alc8500 alc8600 alc9100 ap3250 atx23
   atx24 atx38 bbox bit bitcmyk bitrgb bitrgbtags bj10e bj10v bj10vh bj200
   bjc600 bjc800 bjc880j bjccmyk bjccolor bjcgray bjcmono bmp16 bmp16m
   bmp256 bmp32b bmpgray bmpmono bmpsep1 bmpsep8 ccr cdeskjet cdj1600 cdj500
   cdj550 cdj670 cdj850 cdj880 cdj890 cdj970 cdjcolor cdjmono cdnj500 cfax
   chp2200 cif cljet5 cljet5c cljet5pr coslw2p coslwxl declj250 deskjet
   devicen dfaxhigh dfaxlow display dj505j djet500 djet500c dl2100 dnj650c
  ...
```

Anyone have an idea how to enable the CUPS device to be built?   I don't think that it is as simple as adding    --enable-cups   to the config.

Looking at the Makefile and configure, it might be something to do with dbus... ?

**Comment by ryzhovau** [comment]
Done. MIPSEL binaries in repo, the other will arrive later.
Which platform are you using?

**Comment by davygravy** [comment]
armv7-2.6

Thank you, Alexander.  I will try this when I return home tonight.

**Comment by davygravy** [comment]
Nice!  The patch was effective and my printer did spring to life, suddenly.  

gs -h shows the expected output:
```
gs -h | grep cups
   chp2200 cif cljet5 cljet5c cljet5pr coslw2p coslwxl cups declj250 deskjet
   /opt/share/cups/fonts/ : /opt/share/fonts/
```
In terms of function, I tested it with lp and printing a test page from CUPS... both worked fine.

I'll look now at some other items too, and look for brokenness or weird behavior.   I have been using a cups_2.2.10-2 that I rolled here, for some other reasons... but from here forward, I will revert to using just things from official Entware package feed (like the ghostscript that is now fixed) or compiled from unaltered feed source/Makefiles/patchs, etc.  from here on out.
[ If it ain't broke, don't fix it.]

**Comment by davygravy** [comment]
OK, testing CUPS, I see this:
```
root@AP1:/opt/share/cups/ipptool#  lpr -H 192.168.11.11 testfile.pdf 
lpr: Unsupported document-format "application/pdf".
root@AP1:/opt/share/cups/ipptool#  lpr -H 192.168.11.11 testfile.txt  
lpr: Unsupported document-format "text/plain".
root@AP1:/opt/share/cups/ipptool#  lpr -H 192.168.11.11 testfile.jpg 
lpr: Unsupported document-format "image/jpeg".
root@AP1:/opt/share/cups/ipptool#  lpr -H 192.168.11.11 testfile.ps
lpr: Unsupported document-format "application/postscript".
root@AP1:/opt/share/cups/ipptool#  lpr -H 192.168.11.11 testfile.pcl 
root@AP1:/opt/share/cups/ipptool# lpstat -t
scheduler is running
system default destination: HPC4480
device for HPC4480: socket://127.0.0.1:9100
HPC4480 accepting requests since Wed 17 Apr 2019 01:32:50 PM UTC
printer HPC4480 is idle.  enabled since Wed 17 Apr 2019 01:32:50 PM UTC
root@AP1:/opt/share/cups/ipptool# 
```

In the CUPS interface I see this:
```
E [17/Apr/2019:02:48:57 +0000] [Client 1] Returning IPP client-error-document-format-not-supported for Send-Document (ipp://localhost:631/printers/HPC4480) from localhost.
E [17/Apr/2019:13:31:00 +0000] [Client 4] Returning IPP client-error-document-format-not-supported for Send-Document (ipp://localhost:631/printers/HPC4480) from 192.168.11.11.
E [17/Apr/2019:13:32:18 +0000] [Client 5] Returning IPP client-error-document-format-not-supported for Send-Document (ipp://localhost:631/printers/HPC4480) from 192.168.11.11.
E [17/Apr/2019:13:32:26 +0000] [Client 6] Returning IPP client-error-document-format-not-supported for Send-Document (ipp://localhost:631/printers/HPC4480) from 192.168.11.11.
E [17/Apr/2019:13:32:41 +0000] [Client 7] Returning IPP client-error-document-format-not-supported for Send-Document (ipp://localhost:631/printers/HPC4480) from 192.168.11.11.
```

The problem is missing components in /opt/share from CUPS-filters.  I made a patch that fixes it and will work at minimizing the addition of files/size to the fixed package.

**Comment by davygravy** [comment]
Hi Alexander and zyxmon,

I think/hope this is all that needs to be fixed at this point : three issues, all pretty easy to fix... The changes in item C would bring the size of new_libcups =< size of { sum of entware-ng libcups* } .  For item A, cups-filters, as I show it now, it adds about 70kB, for a total of about 530kB.

A.  **Missing support for USB printers in cups-filters** : cups-filters is missing some necessary components in /opt/share.  Without these, printing fails on many USB printers (perhaps all USB Hewlett Packard inkjet printers, for instance).   I've tested this on my printer and it works as expected.   

- I tried to be very selective about what to copy into the package... very careful about avoiding bloat... about 350kB was avoided.  
- It is my belief (and borne out by some experimentation) that everything in {cupsfilters,charsets,drv,mime,ppdc} is functionally essential.   
- The contents of /opt/share/cups/data are *just two* files that enable a CUPS user to test the CUPS+Filters+Ghostscript+OtherDrivers function, which seemed like small-footprint yet very helpful feature for the end user.


```
diff -aur ./a/Makefile ./b/Makefile
--- ./a/Makefile	2019-04-17 11:08:22.922534934 -0500
+++ ./b/Makefile	2019-04-18 11:28:04.914471191 -0500
@@ -11,7 +11,7 @@
 
 PKG_NAME:=cups-filters
 PKG_VERSION:=1.22.1
-PKG_RELEASE:=1
+PKG_RELEASE:=2
 
 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.bz2
 PKG_SOURCE_URL:=https://github.com/OpenPrinting/cups-filters/releases/download/release-1-22-1
@@ -75,6 +75,14 @@
 	$(CP) $(PKG_INSTALL_DIR)/opt/lib/cups $(1)/opt/lib
 	$(INSTALL_DIR) $(1)/opt/sbin
 	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/opt/sbin/cups-browsed $(1)/opt/sbin
+	$(INSTALL_DIR) $(1)/opt/share/cups/{charsets,data,drv,mime,ppdc}
+	$(INSTALL_DIR) $(1)/opt/share/ppd/cupsfilters
+	$(CP) $(PKG_INSTALL_DIR)/opt/share/ppd/cupsfilters/* $(1)/opt/share/ppd/cupsfilters
+	$(CP) $(PKG_INSTALL_DIR)/opt/share/cups/charsets/* $(1)/opt/share/cups/charsets
+	$(CP) $(PKG_INSTALL_DIR)/opt/share/cups/drv/* $(1)/opt/share/cups/drv
+	$(CP) $(PKG_INSTALL_DIR)/opt/share/cups/mime/* $(1)/opt/share/cups/mime
+	$(CP) $(PKG_INSTALL_DIR)/opt/share/cups/ppdc/* $(1)/opt/share/cups/ppdc
+	$(CP) $(PKG_INSTALL_DIR)/opt/share/cups/data/{default-testpage.pdf,testprint} $(1)/opt/share/cups/data
 endef
 
 $(eval $(call BuildPackage,cups-filters))
```




B.  **liberation-fonts**  :  Printing using `lp` is failing on my USB printer (and I believe for most USB printers) unless at least one font is installed.  The liberation font package in archive is sufficient.  Could you please reinstate liberation-fonts_2.00.1-1_armv7-2.6.ipk  back into the package feed?




C.  **3 libs are missing in libcups** :  
```
libcupsmime.so*
libcupsppdc.so*
libcupscgi.so*
```
are not present in /opt/lib/.

These three libs -are- included in the old packaging system (archives), as three separate packages.  I think its a good idea to roll them into a single package, but perhaps something in the build process (stripping not happening correctly?) is going on.  

Oddly enough 3 distinct binaries (one in each of the mime, ppdc and cgi source/build dirs, IIRC) are --larger-- than they should be, by almost the exact size of the libs that they are associated with.  Could the lib getting "wrapped" into one of those binaries?

**Comment by davygravy** [comment]
Great! & thanks...

I will test this all over from scratch using only vanilla ... on my extra router ASAP and report results back.    Will let you know if everything works as expected.

**Comment by klausrollmann** [comment]
I have the exact same problem. I can help testing if you want.

The fix is simply to build cups-filter and ghostscript from git and download the fonts and libcups* packages from archive? Or am I missing something?

**Comment by ryzhovau** [comment]
> The fix is simply to build cups-filter and ghostscript from git

…to build it with some options. This part already done.

As for fonts, I'll add [dejavu-fonts-ttf](https://github.com/openwrt/packages/blob/master/fonts/dejavu-fonts-ttf/Makefile) as OpenWrt guys do.

**Comment by davygravy** [comment]
With what I see this looks good in terms of function ... Using a fresh install of Entware on armv7sf-k2.6, this is how I tested it:

    opkg install cups-filters ghostscript hplip-full libcups cups dejavu-fonts-ttf-DejaVuSansMono   # CUPS Printing Stack
    nano /opt/etc/cups/cups-files.conf     # see the link below for primer on CUPS server configuration
    nano /opt/etc/cups/cupsd.conf
    cupsd -t            # to check the config files
    /opt/etc/init.d/S60cupsd start

The server/scheduler for CUPS runs as expected, and I accessed the web interface through port 631.  I added my USB printer, set it as the default printer, and was able to print "Test Page" via the webif, which is very nice.

Also tested it with 

     echo  testing  |  lp
which also worked as expected.

@ryzhovau , nicely done, this looks to be Okey-Dokey in terms of working.

My only two questions are sort of 'cosmetic':
1.  I see that when installing the "CUPS Printing Stack" above --without-- the dejavu-font-ttf-DejaVuSansMono package, lp complained to me, saying: 

      "No usable font available"
in the webif -> Jobs, and in /opt/var/log/cups/Error_log there are mentions like:

         W [25/Apr/2019:17:24:11 +0000] [Job 2] Ignored bad font \"monospace\"
         W [25/Apr/2019:17:24:11 +0000] [Job 2] Ignored bad font \"monospace\"
         E [25/Apr/2019:17:24:11 +0000] [Job 2] No usable font available
         ...
         D [25/Apr/2019:17:24:14 +0000] [Job 2] No viable font found
         D [25/Apr/2019:17:24:14 +0000] [Job 2] Set job-printer-state-message to "Ignored bad font \"monospace\"", current level=WARN
         D [25/Apr/2019:17:24:14 +0000] [Job 2] No viable font found
         D [25/Apr/2019:17:24:14 +0000] [Job 2] Set job-printer-state-message to "No usable font available", current level=ERROR
...even though some sort of font package (meta-package?) was pulled in during the opkg install :

     Configuring python.
     Configuring dejavu-fonts-ttf-DejaVuSans.
     Configuring libfreetype.
     Configuring fontconfig.
 


Once I explicitly installed dejavu-fonts-ttf-DejaVuSansMono via 'opkg' , everything seemed very happy and no further errors were generated.

It is my understanding that a font package such as dejavu-fonts-ttf-DejaVuSansMono is only needed if the user wishes to print from the CLI using 'lp'.

NOTE to anyone reading this comment:  a nice primer on CUPS cupsd.conf setup is here:    http://chschneider.eu/linux/server/cups.shtml


2.  Were you intending that the package libcups would have all of the libcups* libraries in the package?  There are only 2 inside (libcups, libcupsimage) and I think 3 libraries are either missing (libcupsppdc, libcupsmime, libcupscgi, or are "wrapped" with some binaries involving those functions.   Everything that I've been able to test --does-- function, but there might be some other applications or functions that expect those 3 libs to be there... I don't know for sure...

**Comment by klausrollmann** [comment]
I am using MIPSEL Kernel 2.6.22 and I just found out that entware dropped support to mips kernel < 3.4. When did that happen? Is there any way I ccould use these packages for mips kernel 2.6?

**Comment by davygravy** [comment]
@klausrollmann  :  It is my understanding that  maurer  @ linksysinfo site ( reference : https://github.com/maurerr/Entware-backports   and   https://www.linksysinfo.org/index.php?threads/mips-repo-entware-backports-entware-ng-reloaded.74337/#post-304426 )  is attempting to address this by backporting some packages ...

You may be able to clone his repo, attempt to refresh the CUPS and print stack ... and bring this to mipselsf-k2.6 ...   I'm not sure how much infrastructure (base or dependent packages) would have to be upgraded... in a near-perfect world, it might be necessary to update only  cups-filters and ghostscript ... but for reference, we know that the current snapshot/versions all interact nicely and function as expected.

Also @klausrollman : Are you intending to run use ghostscript on mipselsf R2 ?  The older chipset perhaps in a router?  If so, I did have Airprint running 'OK' on a Belkin ShareMax N300 for about 5 years... it worked fine for text emails... but graphics sometimes crashed the system because of memory constraints... I had to enable swap ... that's a lot of lifting for such a small CPU.  Possible, feasible, but printing the emails took 20-30 seconds IIRC, rather than being pretty much immediate (like on FreshTomato ARM).

**Comment by ryzhovau** [comment]
> I see that when installing the "CUPS Printing Stack" above --without-- the dejavu-font-ttf-DejaVuSansMono package, lp complained to me, saying:
"No usable font available"

`cups-filters` uses some [hard-coded](https://github.com/Entware/rtndev/commit/bdc3fd15d8157d8604b0daf83f1671764c928035#diff-96cec8527268f6bf1af2c910e5408bb6R49) default font, so I pulled it as as [dependency](https://github.com/Entware/rtndev/commit/bdc3fd15d8157d8604b0daf83f1671764c928035#diff-96cec8527268f6bf1af2c910e5408bb6R29). Looks like I should change it to `dejavu-fonts-ttf-DejaVuSansMono`.

> Were you intending that the package libcups would have all of the libcups* libraries in the package? There are only 2 inside (libcups, libcupsimage) and I think 3 libraries are either missing (libcupsppdc, libcupsmime, libcupscgi, or are "wrapped" with some binaries involving those functions.

I'm still not sure those 3 additional libraries is necessary. We trying to keep `libcups` dependencies on minimal level. I prefer to keep it in current state if it's working as expected.

Thank you for helping me to keep printing stuff is in consistent state.

**Comment by davygravy** [comment]
Happy to help!   Again, thanks to you, zyxmon and others for continuing this project.

**Comment by davygravy** [comment]
> I am using MIPSEL Kernel 2.6.22 and I just found out that entware dropped support to mips kernel < 3.4. When did that happen? Is there any way I ccould use these packages for mips kernel 2.6?

@klausrollmann ,  this issue with Entware-NG (including mipselsf-k2.6) is solved now here :  https://github.com/davygravy/AirPrint-on-Entware/wiki/AirPrint-emulation-on-Entware-with-fewer-hiccups-:-HOWTO

**Comment by klausrollmann** [comment]
@davygravy Thanks for adding support to mipselsf-k2.6.

I followed the tutorial, but still get "Filter failed" when I try to print a test page on cups.

**Comment by davygravy** [comment]
> > Were you intending that the package libcups would have all of the libcups* libraries in the package? There are only 2 inside (libcups, libcupsimage) and I think 3 libraries are either missing (libcupsppdc, libcupsmime, libcupscgi, or are "wrapped" with some binaries involving those functions.
> 
> I'm still not sure those 3 additional libraries is necessary. We trying to keep `libcups` dependencies on minimal level. I prefer to keep it in current state if it's working as expected.
> 

A friendly   FYI @ryzhovau ...  just in case you ever run into a problem looking for these...
I found the reason that those 3 libraries are missing:  a change in  /cgi-bin/Makefile,  
 ppdc/Makefile  and  scheduler/Makefile

The reference/diff   is here : https://fossies.org/diffs/cups/2.2.8-source_vs_2.2.9-source/     in the Makefile section/table.

Now it is clear to me why libraries are no longer generated, apparently by design.  ;)

**Comment by davygravy** [comment]
> @davygravy Thanks for adding support to mipselsf-k2.6.
> 
> I followed the tutorial, but still get "Filter failed" when I try to print a test page on cups

@klausrollmann :  please open an issue at my github repo, so that alex and zyxmon aren't getting spammed by me and you. :)  I'll try to help  you there.  :)
