### ISSUE TITLE
Urgent: bin.entware.net down

### ISSUE THREAD

**Issue by milankragujevic** [Entware/Entware#486]
![image](https://user-images.githubusercontent.com/7611163/85149611-c676f000-b251-11ea-8464-6f7fbbbb22ec.png)

You can see it's not a problem on my end because this is a Cloudflare 522 (Gateway Timeout) error. Same from multiple IPs. 2020-06-19 17:25:00 UTC+2

![image](https://user-images.githubusercontent.com/7611163/85149758-f7efbb80-b251-11ea-8ed9-b2b331a8a0b5.png)

Regular site entware.net (on GH Pages I presume) works. 

This is a huge problem because my device is in the middle of installing Entware when this died, and if I turn it off or there is a power outage it will be bricked.

**Comment by ryzhovau** [comment]
Thanks for report! 

Our hosting is down since 2020-06-19 15:20 UTC after hardware failure. I hope we'll resolve it soon, stay tuned.

**Comment by milankragujevic** [comment]
Can you send me a zip of the "http://bin.entware.net/armv7sf-k2.6/installer" folder, I'll host it locally. I am risking my router's "life", I do not want it to break, I can't reflash it with UART right now. Thanks!

**Comment by zyxmon** [comment]
The installer uses online resources. zip will not help.

**Comment by milankragujevic** [comment]
@zyxmon Actually no, I am using a custom one, it literally only needs these files:

```
http://bin.entware.net/armv7sf-k2.6/installer/opkg
http://bin.entware.net/armv7sf-k2.6/installer/opkg.conf
http://bin.entware.net/armv7sf-k2.6/installer/ld-2.23.so
http://bin.entware.net/armv7sf-k2.6/installer/libc-2.23.so
http://bin.entware.net/armv7sf-k2.6/installer/libgcc_s.so.1
http://bin.entware.net/armv7sf-k2.6/installer/libpthread-2.23.so
```

**Comment by zyxmon** [comment]
If fact now you need only opkg and opkg.conf 
They are here = http://sw.zyxmon.org/tmp/
Installation script is here - https://github.com/Entware/installer.sh

PS You need to edit opkg.conf and generic.sh to point to correct URL

**Comment by zyxmon** [comment]
opkg bynary is static now and does not need *.so files that are left for old scripts compatibility.

**Comment by zyxmon** [comment]
opkg bynary is static now and does not need *.so files that are left for old scripts compatibility.

**Comment by milankragujevic** [comment]
Thank you so much. For others, if your links are gone and this happens again:

[opkg.zip](https://github.com/Entware/Entware/files/4805793/opkg.zip)

**Comment by xRose1** [comment]
I thought it was me that was having issues. Thanks for the updates!

**Comment by TCB13** [comment]
+1 on this.

````
wget http://bin.entware.net/armv7sf-k3.2/installer/generic.sh
Connecting to bin.entware.net (172.67.212.134:80)
wget: server returned error: HTTP/1.1 522 Origin Connection Time-out
````

**Comment by 2b** [comment]
So, there was only one server, without any mirror, right?

**Comment by Ubimo** [comment]
bin.entware.net is up again!

**Comment by zyxmon** [comment]
Fixed.

**Comment by fahaad9** [comment]
Still the same. i tried running opkg update but get wget returned 8.
